### PR TITLE
Fix 1000000 and add 1000001

### PR DESCRIPTION
**Pull request by ChrisTTian667**

### CODE REVIEW

**Comment by 17radf** [comment]
lmfao

**Review by niltonfrederico — APPROVED** [review]
LGTM!

**Review by 17radf — APPROVED** [review]

**Review by JeanJPNM — APPROVED** [review]

**Comment by ChrisRx** [comment]
I really need 1,000,001 would love to see this get merged!

**Comment by lz-censys** [comment]
> I really need 1,000,001 would love to see this get merged!

I think it should be held off until testing is done.

**Comment by samuelmarina** [comment]
Thank you, the community appreciates your effort

**Pull request merged**
