### PR TITLE
Create C++MakesItEasy.cpp

### PR DESCRIPTION
**Pull request by Shu6hamPrasad**
Just enter the number of conditions and it will write the file for you :-)
You are a NOOB ;-)

### CODE REVIEW

**Comment by Shu6hamPrasad** [comment]
i tried to upload 10000000 lines but the file size became almost 400 mbs so I made this

**Comment by dogtopus** [comment]
It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.

**Comment by Shu6hamPrasad** [comment]
> It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.

maybe next release i'll try it. Thanks!

**Comment by Shu6hamPrasad** [comment]
> It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.

btw what do you mean by "add conditions for write out numbers" ?

**Comment by dogtopus** [comment]
> > It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.
> 
> btw what do you mean by "add conditions for write out numbers" ?

It's added in #69 where you can write out the number as a word like `twenty` and it will be processed as if it was a number. We can expand on that so `one million two hundred thirty four thousand five hundred sixty seven` will be treated as `1234567` for example.

**Comment by Shu6hamPrasad** [comment]
> > > It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.
> > 
> > 
> > btw what do you mean by "add conditions for write out numbers" ?
> 
> It's added in #69 where you can write out the number as a word like `twenty` and it will be processed as if it was a number. We can expand on that so `one million two hundred thirty four thousand five hundred sixty seven` will be treated as `1234567` for example.

is this possible in cpp?
(you cannot automate texts....)

**Comment by dogtopus** [comment]
> > > > It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.
> > > 
> > > 
> > > btw what do you mean by "add conditions for write out numbers" ?
> > 
> > 
> > It's added in #69 where you can write out the number as a word like `twenty` and it will be processed as if it was a number. We can expand on that so `one million two hundred thirty four thousand five hundred sixty seven` will be treated as `1234567` for example.
> 
> is this possible in cpp?
> (you cannot automate texts....)

It should be possible with a routine that converts the number to phrase and just write both of them to the generated js file.

**Comment by Shu6hamPrasad** [comment]
> > > > > It would be great if you can add conditions for write out numbers and auto file split on 100MB mark.
> > > > 
> > > > 
> > > > btw what do you mean by "add conditions for write out numbers" ?
> > > 
> > > 
> > > It's added in #69 where you can write out the number as a word like `twenty` and it will be processed as if it was a number. We can expand on that so `one million two hundred thirty four thousand five hundred sixty seven` will be treated as `1234567` for example.
> > 
> > 
> > is this possible in cpp?
> > (you cannot automate texts....)
> 
> It should be possible with a routine that converts the number to phrase and just write both of them to the generated js file.
> 
> (I wrote one for an assignment before. It's not so trivial and requires a bit of tinkering for the edge cases but it's possible.)

can you do it?
I can do the file splitting part
but now they added the support for roman number!
F

**Comment by dogtopus** [comment]
yes it's probably easier to do these using higher level languages and perhaps with a library

**Comment by Shu6hamPrasad** [comment]
> yes it's probably easier to do these using higher level languages and perhaps with a library

my code is made on c++

**Comment by Shu6hamPrasad** [comment]
> yes it's probably easier to do these using higher level languages and perhaps with a library
> 
> (~someone mentioned [finnfiddle/words-to-numbers](https://github.com/finnfiddle/words-to-numbers) in the discussions section which does the conversion for you. It's js though~ OK it's backwards. So not converting from a integer to a phrase)

hey that'd work we can convert the phrase to integers and then go for conditions...
 but how can we integrate these files?

**Comment by OakleyCord** [comment]
> Just enter the number of conditions and it will write the file for you :-)
> You are a NOOB ;-)

you got to do it like a real programmer and write it manually

**Comment by Shu6hamPrasad** [comment]
> > Just enter the number of conditions and it will write the file for you :-)
> > You are a NOOB ;-)
> 
> you got to do it like a real programmer and write it manually 

F u

**Pull request closed without merging**
