### PR TITLE
Check if number is actually even

### PR DESCRIPTION
**Pull request by gingerbenw**
Important use case to check if the provided number is actually even

### CODE REVIEW

**Comment by soosgyul** [comment]
Yes! We need this!

**Comment by RichardD2** [comment]
Doesn't work for 93.75% of "even" strings:
```
isEven("Even") === false
```

**Comment by taha-ghadirian** [comment]
Please implement this peace of sheets: 
Even-EVEN-eVen-evEn-eveN-EVen-EvEn-EveN-EVEn-EVeN-
And other strings...

**Comment by samuelmarina** [comment]
> Please implement this peace of sheets:
> Even-EVEN-eVen-evEn-eveN-EVen-EvEn-EveN-EVEn-EVeN-
> And other strings...

I agree. Add this and I will merge

**Comment by gingerbenw** [comment]
Updated to check that it's _definitely_ even

**Review by taha-ghadirian — APPROVED** [review]

**Comment by taha-ghadirian** [comment]
> Updated to check that it's _definitely_ even

GoOoOoOoD job man!

**Comment by samuelmarina** [comment]
My mind is telling me no, but my body, my body is telling my yeah

**Pull request merged**
