### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by taha-ghadirian**
Thanks fucking contributers!

### CODE REVIEW

**Comment by taha-ghadirian** [comment]
@lorem10 Fucking vote up this silly fucking PR!!

**Comment by SJM96** [comment]
plz no

**Comment by taha-ghadirian** [comment]
> plz no

Yes UR right! Fuck them all ;)

**Comment by adityasuman2025** [comment]
fuck no

**Comment by taha-ghadirian** [comment]
> fuck no

U R fucking right!
fuk all of them!

**Comment by adityasuman2025** [comment]
luv u frand

**Pull request closed without merging**
