### PR TITLE
Add support for negative numbers.

### PR DESCRIPTION
**Pull request by SrijanSriv211**
I added the support for negative numbers but due to GitHub storage limitation i wasn't able to add more.

### CODE REVIEW

**Comment by TechyAditya** [comment]
what is the storage limitation?

**Comment by Light-Lens** [comment]
The storage limitation is that i cannot upload a file with more than 100 megabytes of data.

**Comment by Light-Lens** [comment]
> what is the storage limitation?

The storage limitation is that i cannot upload a file with more than 100 megabytes of data.

**Comment by SrijanSriv211** [comment]
> what is the storage limitation?

The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.

**Comment by SaptakBhoumik** [comment]
> > what is the storage limitation?
> 
> The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.
> 

Use git push for uploading larger files

**Comment by SrijanSriv211** [comment]
> > > what is the storage limitation?
> > 
> > 
> > The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.
> 
> Use git push for uploading larger files

I tried using git, but an error occurred saying, failed to push some refs to..

**Comment by TechyAditya** [comment]
> > > what is the storage limitation?
> > 
> > The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.
> > 
> 
> Use git push for uploading larger files

Git push won't work for files larger than 100 mb. There's only one way to upload files more than 100 mb, uploading as release. GitHub allows upto 2 gb of file upload if you upload it as a release.

**Comment by Light-Lens** [comment]
> > > > what is the storage limitation?
> > > 
> > > 
> > > The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.
> > 
> > 
> > Use git push for uploading larger files
> 
> Git push won't work for files larger than 100 mb. There's only one way to upload files more than 100 mb, uploading as release. GitHub allows upto 2 gb of file upload if you upload it as a release.

That's a good choice, but one day even GitHub release will fail as you said allows only upto 2 GB, but i can use this method for now. Thanks :)

**Comment by SrijanSriv211** [comment]
> > > > what is the storage limitation?
> > > 
> > > 
> > > The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.
> > 
> > 
> > Use git push for uploading larger files
> 
> Git push won't work for files larger than 100 mb. There's only one way to upload files more than 100 mb, uploading as release. GitHub allows upto 2 gb of file upload if you upload it as a release.

That's a good choice, but one day even GitHub release will fail as you said allows only upto 2 GB, but i can use this method for now. Thanks :)

But if possible then please accept this pull request, vs code crashed 3 times while editing this file as i have a low end pc. I worked pretty hard on it. Hope you understand, again thanks for cooperating.

**Comment by bhpcv252** [comment]
How about dividing the file into many small files, then we can continue.

**Comment by SaptakBhoumik** [comment]
You are right

**Comment by SrijanSriv211** [comment]
> You are right

Yes, this seems a good idea, though!

**Comment by 0xMukesh** [comment]
> > what is the storage limitation?
> 
> The storage limitation is that i cannot upload a file with more than 100 megabytes of data on GitHub.

use [git lfs](https://git-lfs.github.com/) 
git lfs is made for programmers like us to develop modules which will make this earth a better place

**Pull request closed without merging**
