### PR TITLE
Do not be a idiot, use code that performs great

### PR DESCRIPTION
**Pull request by MarcelDev**

### CODE REVIEW

**Review by lamergameryt — COMMENTED** [review]
Is this what they teach in WhiteHat Jr.? We all know real programmers write everything by themselves.

**Comment by samuelmarina** [comment]
an*

**Comment by northmatt** [comment]
I find a lot of the serious answers here generally got an okay amount of mistakes.

Ideally one would want to avoid unneeded branching, and if one were to branch then to avoid `else` statements wherever possible due to how CPUs optimize `if` statements. Also would be better to use bitwise over modulo for this scenario.

```
function IsEven(num) {	
    return !(num & 1);
}
```

**Comment by MarcelskyXD** [comment]
> an*

Go kill yourself

**Pull request closed without merging**
